### ISSUE TITLE
Cannot declare class Coinpayments, because the name is already in use

### ISSUE THREAD

**Issue by darkin1** [kevupton/laravel-coinpayments#1]
When I want to execute unit tests (phpunit) I getting error like below 

```
ErrorException: Cannot declare class Coinpayments, because the name is already in use

/app/api/vendor/kevupton/laravel-coinpayments/src/Kevupton/LaravelCoinpayments/Providers/LaravelCoinpaymentsServiceProvider.php:27
```

To fix it override `class_alias` like this 

```
if(!class_exists('Coinpayments')){
    class_alias(Coinpayments::class, 'Coinpayments');
}
```

Of course do it in `vendor/kevupton/laravel-coinpayments/src/Kevupton/LaravelCoinpayments/Providers/LaravelCoinpaymentsServiceProvider.php` file

**Comment by kevupton** [comment]
Thanks for letting me know, I just implemented a fix for this. in `v0.2.6`
