### ISSUE TITLE
Call to undefined function ..\LaravelPackageServiceProvider\config_path() on Lumen 5.6

### ISSUE THREAD

**Issue by S0PEX** [kevupton/laravel-coinpayments#11]
Hey, I just wanted to let you know that if you are using this package with the latest lumen version this error is thrown : 
![img](https://puu.sh/zQQqw/a3d588ea4c.png)

you can simply fix this error when you add a public config_path function for Lumen framework
like this: 
```php 
<?php
if ( ! function_exists('config_path'))
{
    /**
     * Get the configuration path.
     *
     * @param  string $path
     * @return string
     */
    function config_path($path = '')
    {
        return app()->basePath() . '/config' . ($path ? '/' . $path : $path);
    }
} 
```

then go to composer.json and add this file to autoload, so that it looks like this:
```JSON
"autoload": {
    "psr-4": {
        "App\\": "app/"
    },
    "files": [
        "app/helpers/helpers.php" ---path/path/yourfile.php
    ]
},
```

And last but not least run composer `dump-autoload` to load the newly created helper's file.

Regards S0PEX

**Comment by kevupton** [comment]
Awesome thanks for letting me know.

**Comment by kevupton** [comment]
This should be fixed in v1
