### ISSUE TITLE
IPN Not Working

### ISSUE THREAD

**Issue by JesseMCFC** [kevupton/laravel-coinpayments#15]
I've followed the README & Configured everything correctly. But in the Coinpayments IPN History I can see that it is unable to deliver the IPN. Are there steps required that are not in the ReadMe?

**Comment by kevupton** [comment]
Check to make sure that your IPN url is accessible by the coinpayments server.
You can do this by using [PostMan](https://www.getpostman.com/).

Just send a POST request to your IPN url. 
By default it is `{yourServerHost}/api/ipn`

If you dont get a 404 then the route is configured correctly.

------

Also check to see if you have any logs in your database in the table `cp_log`.

Let me know what you get back.

**Comment by JesseMCFC** [comment]
Thanks for answering. I've mailed CoinPayments yesterday and I've received this answer:

> Hi Jesse,
> 
> Yes, you can see it in your HTTP/PHP error logs and any debug emails or logs you have it sending you/writing. I re-sent one of your recent IPNs and your server returned this:
> 
> SQLSTATE[23000]: Integrity constraint violation: 1048 Column &#039;amount&#039; cannot be null (SQL: update `cp_transactions` set `
> amount` = , `address` = , `updated_at` = 2018-04-17 20:44:00, `status` = 0, `status_text` = Waiting for buyer funds... where `id` = 52) in file vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 664

Im going to look into it myself and see if I can tackle the issue.

**Comment by JesseMCFC** [comment]
Was unable to fix this myself. Looking forward to hear your answer.


EDIT:

Found the issue is somewhere in the validateIPN function. I've modified it so it suits my purpose but definitely something to look into. Anyway keep up the good work 👍

**Comment by kevupton** [comment]
ahh, this looks like a migration problem.
What kind of IPN was it for? Was it a Transaction, Deposit or Withdrawal ?

**Comment by JesseMCFC** [comment]
Transaction.

**Comment by kevupton** [comment]
This is fixed in `v1.0.1`
