### ISSUE TITLE
The api/ipn returns status 400

### ISSUE THREAD

**Issue by saviobosco** [kevupton/laravel-coinpayments#17]
The default 'apn/ipn' returns a 400 or 419 status when hit by coinpayment generator server .

**Comment by kevupton** [comment]
do you have any error logging or response information regarding the request?

**Comment by dotintechno** [comment]
@kevupton  I also experience the same issues. There are no errors in the log file or the log table.
![screen shot 2018-07-26 at 10 37 42 am](https://user-images.githubusercontent.com/34878080/43242669-0b681e74-90c0-11e8-98a6-67224130548b.png)
![screen shot 2018-07-26 at 10 37 20 am](https://user-images.githubusercontent.com/34878080/43242676-18f6d134-90c0-11e8-8465-a6c324126176.png)

Only Transaction complete ipn recieves 200 status. The issue with this is when Coinpayment ping again with failed ipn the status of the transaction get changed.
This is the transaction table when it recieves the transaction complete ipn
![screen shot 2018-07-26 at 10 40 37 am](https://user-images.githubusercontent.com/34878080/43242853-f4e2bdfc-90c0-11e8-8dcf-61e11f36457b.png)
But when they ping again with the failed ipns status changed
![screen shot 2018-07-26 at 10 41 24 am](https://user-images.githubusercontent.com/34878080/43242879-1737a19c-90c1-11e8-8756-7681474f7818.png)
I dont know if its intensional or not can you help me out?
