### ISSUE TITLE
Withdrawal info missed

### ISSUE THREAD

**Issue by sklazer** [kevupton/laravel-coinpayments#19]
Hi,

First of all - thanks for the great package! Working great!

Want to propose to add "withdrawal info" functionality - it would be very helpful to get withdrawal information after sending funds.

All documents you can find here:
https://www.coinpayments.net/apidoc-get-withdrawal-info

Thank you and have a good day!

**Comment by kevupton** [comment]
Thanks! 😄 
I have merged your PR, and just renamed the function from `withdrawalInfo` to `getWithdrawalInfo`,
The new changes with be in the new version. `v1.1.2`,

**Comment by sklazer** [comment]
You are welcome :) Thanks again for great package!
