### ISSUE TITLE
package not installing

### ISSUE THREAD

**Issue by p-drolima** [kevupton/laravel-coinpayments#2]
Hi,

I have followed normal proceedures for installing a package and in particular your instructions but I am getting thrown an exception when running "php artisan vendor:publish"

'providers' => [
    // Other Service Providers

    \Kevupton\LaravelCoinpayments\Providers\LaravelCoinpaymentsServiceProvider::class,
],

any ideas??

Thank you,

Pedro

**Comment by kevupton** [comment]
Hey,
What version of laravel /lumen are you using ?  
Also what is the error message you are getting ?
