### ISSUE TITLE
No Destination Tag for Ripple, Monero

### ISSUE THREAD

**Issue by fullmad** [kevupton/laravel-coinpayments#22]
No destination tag for ripple, monnero while doing createTransactionSimple() return. So how to deposit XRP ?

**Comment by kevupton** [comment]
Are you looking for the deposit address ? 
I believe that is on the `Transaction` model under `address`

```php 
$transaction->address;
```

**Comment by kevupton** [comment]
I just merged #21 which will give support for this functionality I believe. 

Released in `v1.1.3`
