### ISSUE TITLE
USD does not support withdrawals!

### ISSUE THREAD

**Issue by rotimiolaosebikan** [kevupton/laravel-coinpayments#32]
I am trying to create a withdrawal from the admin page, but USD does not support withdrawals error was triggered.

$withdraw = Withdrawal::findOrFail($id);
        
        if (!$withdraw->paid) {
            $response = Coinpayments::createWithdrawal($withdraw->amount - ($withdraw->amount * 1 / 100), "USD", $withdraw->wallet_address, true);
            
            if ($response) {
                $withdraw->paid = true;
                $withdraw->status = 1;
                $withdraw->save();
            } else {
                return redirect()
                    ->back()
                    ->with('message', 'Unable to mark the withdrawal paid');
            }
        }

I got the exception details below

Kevupton \ LaravelCoinpayments \ Exceptions \ CoinPaymentsResponseError
USD does not support withdrawals!

**Comment by kevupton** [comment]
Hmmm is USD supported as a withdrawal on coinpayments?
