### ISSUE TITLE
Withdrawal is not automatic.

### ISSUE THREAD

**Issue by fullmad** [kevupton/laravel-coinpayments#34]
Withdrawal is not automatic. Every time I make a withdrawal, Coinpayments sends a confirmation email to admin.. also when trying to do conversion, I am getting fatal error like: Unknown method convertCoins

**Comment by suzandi** [comment]
Actually, it is:
at function ->
` createWithdrawal ($amount, $currency, $address, $autoConfirm = false, $ipnUrl = '')`
If you set the 4th parameter to 1, the withdrawal will be sent without email confirmation.
