### ISSUE TITLE
The IPN is not working. It's not returning the IPN url

### ISSUE THREAD

**Issue by devsahm** [kevupton/laravel-coinpayments#37]

**Comment by devsahm** [comment]
I am not getting the IPN response. Am I doing something wrong? I really need help

**Comment by devsahm** [comment]
I can only verify the transaction status manually with this
\Coinpayments::getTransactionInfo($request->txn_id)

However, I want to be able to get the IPN automatically instead of doing it manually.. I look forward to seeing your response, thanks in advance

**Comment by kevupton** [comment]
Hey sorry for the slow response, 
Did you end up getting this sorted?

**Comment by devsahm** [comment]
Yes, I figured out another way.. Thanks
