### ISSUE TITLE
[FR] more verbose README "usage" section

### ISSUE THREAD

**Issue by ITwrx** [kevupton/laravel-coinpayments#4]
Feel free to "won't fix" this issue. but when trying to implement IPN (more directly) for the first time it can be difficult to put it all together. It would probably be helpful, for some, if the usage section of the README were a little more verbose. 

A transaction scenario(s) with more verbose comments. ex: a product/donation button that works with this package. You rightly show only the part that has to do with this package in the simple transaction example, but more context might make things clearer. It took me a little while to realize that you could set the IPN url in a few different places, for instance. Also, the IPN_url route needed for coinpayments.net's reply is unclear if you've never done it before. More complete example implementations, showing the whole chain of events/process, including the stuff that seems like it should be glaringly obvious or is even, technically, outside of scope, would be nice. 

thanks

**Comment by kevupton** [comment]
Ok, no problem, 
Thanks for the feedback, Ill look at updating the docs 😄 
Maybe ill make an example repo as well.

**Comment by kevupton** [comment]
I have created this:
https://github.com/kevupton/example-laravel-coinpayments

And also added a controller to the readme. Let me know if that looks better

**Comment by ITwrx** [comment]
Thanks for all that! It does look helpful for api use. I'm starting to think my confusion is just me though. :(  

@kevupton 
update: things are starting to make sense for my current use case now. 

this package: 

https://github.com/TaylorChristie/CoinPayments 

is exactly what i need (feature wise) right this second, but it isn't updated for latest CP API usage. After reading it's examples, now i understand your controller example in my app's context (duh!) and should be able to use laravel-coinpayments as a simple gateway. If i have any useful doc suggestions once i get it working, i'll send them your way. 

thanks

**Comment by AricShelby** [comment]
Kev, I second some more context to the package.  I have scratched the surface here with MariaDB, and also couldn't get the migrate to work. (Laravel 5.5) Had to load it into the database folder manually and it then migrate worked.  But then couldn't figure out why the tables don't populate when transactions occur... it appears I need to program that logic and setup some Models too for eloquent.  The Config file also didn't work when I did vendor:publish.  Copied manually and it's good.  I installed through Composer...  Got it mostly working, after working through some issues, still your package will save lots of time, so thanks.  However, more context on the readme would be helpful.  Thanks again!

**Comment by ITwrx** [comment]
@mojpoj he fixed the migration issue by setting a shorter default string length, so any new package installation's migration should work now. If you had trouble with the migration, and now data is not going in the DB, it might be worth trying to start over with a copy that has that commit. vendor:publish worked fine for me.

**Comment by AricShelby** [comment]
I got the migrate to work correctly, however, a couple points...

From the setup instructions:

`\Coinpayments::createTransactionSimple($cost, $currency_base, $currency_received, $extra_details);
`
That ^ does not work for me in Laravel 5.5.  
If I new up the class and then call the method it works...

```
$coinPayment = new Coinpayments($this->cPrivateKey, $this->cPublicKey, $this->cMerch, $this->cIPNSec, $this->cIPNAddy, $this->cFormat);
$transaction = $coinPayment->createTransactionSimple(.11, 'LTCT', 'LTCT', ['buyer_email' => 'testuser@test.com']);
```

But that requires pulling the setup variables as $this (from env) at the top of my controller to pass to the coinpayments controller.   

And the tables are still _not being populated_ when I create a transaction.

Also this from the readme is invalid... 

`\Coinpayments::validateIPNRequest($request);`

It should read \Coinpayments::validateIPN($request);  (not validateIPNRequest($request).

**Comment by ITwrx** [comment]
@kevupton i'm closing this as i don't even need the coinpayments API currently. i only need to create buttons and validate the IPNs that come in. Also, the source is well documented with easy to follow naming, so it's not really a documentation issue for me like i thought it was. I was just stuck in consumer mode and didn't realize it. :)
thanks
