### ISSUE TITLE
Change Receipt.php Private variables to Public

### ISSUE THREAD

**Issue by AricShelby** [kevupton/laravel-coinpayments#5]
I believe those Private variables are giving me grief and throwing an Exception when setting up a test transaction in my controller like this...

```
$coinPayment = new Coinpayments($this->cPrivateKey, $this->cPublicKey, $this->cMerch, $this->cIPNSec, $this->cIPNAddy, $this->cFormat);
$transaction = $coinPayment->createTransactionSimple(.11, 'LTCT', 'LTCT', ['buyer_email' => 'testuser@test.com']);
dd($transaction->response);
```

I get: Cannot access private property Kevupton\LaravelCoinpayments\Receipt::$response

Perhaps I'm not accessing the result the right way.  I need the response to feed it into the transaction model for storing.

If I dd($transaction); I get the receipt model fine.

Thanks!

**Comment by kevupton** [comment]
Hey @mojpoj , what are you looking to get  from the response ? 
At the moment the response is transformed into either a `Transaction`, a `Withdrawal` or a `Transfer` model.
So in the above case you will just have the `Transaction` model which contains all of the information for that transaction.

**Comment by kevupton** [comment]
Oh @mojpoj I see you are using the Coinpayments class directly. 
If you use the Facade, `\Coinpayments` it will return a `Transaction` model.

As for the `Receipt` those properties are not accessible directly, however they do have getters:
```php
$reciept->getResponse();
```
