### ISSUE TITLE
minor uninstall error

### ISSUE THREAD

**Issue by ITwrx** [kevupton/laravel-coinpayments#6]
i received a minor error when trying to uninstall, just fyi. 

i removed the laravel-coinpayments line from composer.json and the provider line from config/app.php, then ran "composer update". i got the following:

``` > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In coinpayments.php line 28:
                                                             
  Class 'Kevupton\LaravelCoinpayments\Models\Log' not found  
                                                             

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

**Comment by kevupton** [comment]
Interesting, sorry I have been away on holidays,
I will check this out.

**Comment by ghost** [comment]
@ITwrx remove `app/coinpayments.php` and error will be solved.
@kevupton add `app/conipayments.php` removal with `composer remove` command

**Comment by kevupton** [comment]
I believe @EvaldasAlcauskis is right, simply deleting the left over config file should make this work.

**Comment by ITwrx** [comment]
@kevupton yes, i had already done that when i posted this issue. I just thought that the package should clean up after itself, so i figured that was a bug you might want to know about/feature you may want to add. 
@EvaldasAlcauskis has described how you could do it if you wanted. I didn't know how "off the top of my head" or i would have mentioned it.
thanks

**Comment by kevupton** [comment]
@ITwrx thanks for letting me know. 
It would be cool if the plugin could auto clean up, but I couldnt find any way to do this 😞

**Comment by ITwrx** [comment]
@kevupton i think i was just supposed to run 'composer remove' instead of 'composer update'. i still don't know if that will remove a published config file, though. not a big deal either way. i was just curious mainly. :)
