### ISSUE TITLE
How is 'confirmations received' column updated?

### ISSUE THREAD

**Issue by devWaleed** [kevupton/laravel-coinpayments#9]
Hey, I have some questions regarding confirmations received. How exactly is this updated? Does it update on IPN request or on getTransactionInfo? For BTC/ETH I have seen it shows 3 in the column. 

Can you please explain a bit.

Thanks

**Comment by kevupton** [comment]
At the moment, confirmations are only updated on IPN request and are located on the IPN model. 
This happens when you call `\Coinpayments::validateIPNRequest` or `Coinpayments::validateIPN`

If there have been enough confirmations and payment is complete, then no exceptions will be thrown from those functions.

**Comment by devWaleed** [comment]
Is it possible to add a method/parameter to update transactions tables with getTransactionInfo() method with the latest transaction status? without IPN response as a second way of updating transaction statuses.

I asked coinpayments via a ticket and their response about IPN is that it only sends after payment is done but not for each/any received confirmations after that. Wouldn't it be better if we could use getTransactionInfo with an additional parameter to also update received confirmations and other info?

Also, how will it deal with the incomplete payments. For example: If for a transaction 1 BTC is the payment and in my first transaction I send only 0.5 BTC? Later I send remaining with fee to complete. How will it deal with this type of behavior?

Thanks.

**Comment by kevupton** [comment]
From what I understand about coinpayments, is the payment request has a timeout. So if the money is received after that timeout, then it will not be recognised as a payment. I believe this timeout is fairly long, maybe around 2.5 hrs. Not 100% sure on its length. 

As for the get transaction info, I do think that it is somthing that shouldnt be too hard to implement. I agree that it would be good to have it update the IPN on the return of the get txn response, or even just update the transaction model to present the current number of confirms.

Ill add it in amongst the fixes for the config file.

**Comment by devWaleed** [comment]
I was thinking if confirms received is 0 at the time of IPN and it is actually needed to confirm payments, since Coinpayments doesn't send IPN for each confirm they get from block chains, I think IPN is useless for crypto payments. Instead I am going to use getTransactionInfo for getting all transaction status and update manually. Do you think IPN is useful in anyway?

**Comment by kevupton** [comment]
The main thing the IPN would be used for is doing something once the payment is complete. 
An example would be a user buying credit for a platform. We wont actually transfer the credit until we get an IPN saying that the payment is complete. 
The IPN just saves us having to continuously ping their server, checking to see if the payment is done. 
Im not sure what you are planning to build, but I would say most of the time, the IPN is the most appropriate way of doing things.

**Comment by kevupton** [comment]
this will be implemented in v1

**Comment by kevupton** [comment]
This is now implemented 🎈
